<?php

namespace tud\Plugins\VerDatAsDsh\Utils;

use tud\Plugins\VerDatAsDsh\Repository;

/**
 * Trait VerDatAsDshTrait
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package tud\Plugins\VerDatAsDsh\Utils
 *
 * @author tud <tommy.kubica@tu-dresden.de>
 * @author fluxlabs <support@fluxlabs.ch>
 */
trait VerDatAsDshTrait
{

    /**
     * @return Repository
     */
    protected static function verDatAsDsh() : Repository
    {
        return Repository::getInstance();
    }
}
