<?php

namespace tud\Plugins\VerDatAsDsh;

use tud\Plugins\VerDatAsDsh\Config\Repository as ConfigRepository;
use tud\Plugins\VerDatAsDsh\Utils\VerDatAsDshTrait;
use ilVerDatAsDshPlugin;
use srag\DIC\VerDatAsDsh\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package tud\Plugins\VerDatAsDsh
 *
 * @author tud <tommy.kubica@tu-dresden.de>
 * @author fluxlabs <support@fluxlabs.ch>
 */
final class Repository
{

    use DICTrait;
    use VerDatAsDshTrait;

    const PLUGIN_CLASS_NAME = ilVerDatAsDshPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    private function __construct()
    {

    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @return ConfigRepository
     */
    public function config() : ConfigRepository
    {
        return ConfigRepository::getInstance();
    }


    /**
     *
     */
    public function dropTables() : void
    {
        $this->config()->dropTables();
    }


    /**
     *
     */
    public function installTables() : void
    {
        $this->config()->installTables();
    }
}
