<?php

require_once __DIR__ . "/../vendor/autoload.php";

use tud\Plugins\VerDatAsDsh\Config\ConfigCtrl;
use tud\Plugins\VerDatAsDsh\Utils\VerDatAsDshTrait;
use srag\DevTools\VerDatAsDsh\DevToolsCtrl;
use srag\DIC\VerDatAsDsh\DICTrait;

/**
 * Class ilVerDatAsDshConfigGUI
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author tud <tommy.kubica@tu-dresden.de>
 * @author fluxlabs <support@fluxlabs.ch>
 */
class ilVerDatAsDshConfigGUI extends ilPluginConfigGUI
{

    use DICTrait;
    use VerDatAsDshTrait;

    const CMD_CONFIGURE = "configure";
    const PLUGIN_CLASS_NAME = ilVerDatAsDshPlugin::class;


    /**
     * ilVerDatAsDshConfigGUI constructor
     */
    public function __construct()
    {

    }


    /**
     * @inheritDoc
     */
    public function performCommand(/*string*/ $cmd) : void
    {
        $this->{$cmd}();
    }


    protected function configure(ilPropertyFormGUI $form = null)
    {
        global $DIC;
        /* @var \ILIAS\DI\Container $DIC */

        // TODO: Get $plugin_object and use txt-attribute
        if (!count(ilCmiXapiLrsTypeList::getTypesData(false))) {
            ilUtil::sendFailure('Before proceeding with the configuration, please add an xAPI type using the "xAPI/cmi5" submenu.');
            return;
        }

        if ($form === null) {
            $form = $this->buildForm();
        }

        $DIC->ui()->mainTemplate()->setContent($form->getHTML());
    }

    protected function save()
    {
        global $DIC;
        /* @var \ILIAS\DI\Container $DIC */

        $form = $this->buildForm();

        if (!$form->checkInput()) {
            return $this->configure($form);
        }

        $this->writeBackendURL($form->getInput('backend_url'));
        $this->writeLrsTypeId($form->getInput('lrs_type_id'));
        $this->writeUseApi($form->getInput('use_api'));

        $DIC->ctrl()->redirect($this, 'configure');
    }

    protected function buildForm() : ilPropertyFormGUI
    {
        global $DIC;
        /* @var \ILIAS\DI\Container $DIC */

        $form = new ilPropertyFormGUI();

        $form->setFormAction($DIC->ctrl()->getFormAction($this));
        $form->addCommandButton('save', $DIC->language()->txt('save'));

        $form->setTitle('Configuration');

        // Backend URL
        $backendURLItem = new ilTextInputGUI('Backend URL', 'backend_url');
        $backendURLItem->setRequired(true);

        $backendURLItem->setValue($this->readBackendURL());

        $form->addItem($backendURLItem);

        // LRS type
        $lrsTypeItem = new ilRadioGroupInputGUI('LRS-Type (define type of user identification)', 'lrs_type_id');
        $lrsTypeItem->setRequired(true);

        # $types = ilPluginAdmin::isPluginActive("xxcf") ? ilLp2LrsChangesQueue::getTypesData() : ilCmiXapiLrsTypeList::getTypesData(false);
        $types = ilCmiXapiLrsTypeList::getTypesData(false);

        foreach ($types as $type) {
            $option = new ilRadioOption($type['title'], $type['type_id'], $type['description']);
            $lrsTypeItem->addOption($option);
        }

        $lrsTypeItem->setValue($this->readLrsTypeId());

        $form->addItem($lrsTypeItem);

        // Use API
        $useApiItem = new ilRadioGroupInputGUI('Use API (if installed)', 'use_api');
        $useApiItem->setRequired(true);

        $optionTrue = new ilRadioOption('True', 1, '');
        $optionFalse = new ilRadioOption('False', 0, '');
        $useApiItem->addOption($optionTrue);
        $useApiItem->addOption($optionFalse);

        $useApiItem->setValue($this->readUseApi());

        $form->addItem($useApiItem);

        return $form;
    }

    protected function readBackendURL()
    {
        $settings = new ilSetting(ilVerDatAsDshPlugin::PLUGIN_ID);
        return $settings->get('backend_url');
    }

    protected function writeBackendURL($backendURL)
    {
        $settings = new ilSetting(ilVerDatAsDshPlugin::PLUGIN_ID);
        $settings->set('backend_url', $backendURL);
    }

    protected function readLrsTypeId()
    {
        $settings = new ilSetting(ilVerDatAsDshPlugin::PLUGIN_ID);
        return $settings->get('lrs_type_id', 0);
    }

    protected function writeLrsTypeId($lrsTypeId)
    {
        $settings = new ilSetting(ilVerDatAsDshPlugin::PLUGIN_ID);
        $settings->set('lrs_type_id', $lrsTypeId);
    }

    protected function readUseApi()
    {
        $settings = new ilSetting(ilVerDatAsDshPlugin::PLUGIN_ID);
        return $settings->get('use_api', 0);
    }

    protected function writeUseApi($useApi)
    {
        $settings = new ilSetting(ilVerDatAsDshPlugin::PLUGIN_ID);
        $settings->set('use_api', $useApi);
    }
}
