<?php

require_once __DIR__ . "/../vendor/autoload.php";

use tud\Plugins\VerDatAsDsh\Utils\VerDatAsDshTrait;
use ILIAS\DI\Container;
use srag\CustomInputGUIs\VerDatAsDsh\Loader\CustomInputGUIsLoaderDetector;
use srag\DevTools\VerDatAsDsh\DevToolsCtrl;
use srag\RemovePluginDataConfirm\VerDatAsDsh\PluginUninstallTrait;

/**
 * Class ilVerDatAsDshPlugin
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author tud <tommy.kubica@tu-dresden.de>
 * @author fluxlabs <support@fluxlabs.ch>
 */
class ilVerDatAsDshPlugin extends ilPageComponentPlugin
{

    use PluginUninstallTrait;
    use VerDatAsDshTrait;

    const PLUGIN_CLASS_NAME = self::class;
    const PLUGIN_ID = "vdsh";
    const PLUGIN_NAME = "VerDatAsDsh";
    const GET_PARAM_REF_ID = "ref_id";
    const GET_PARAM_TARGET = "target";

    /**
     * @var self|null
     */
    protected static $instance = null;

    /**
     * @var int|null
     */
    protected static $current_ref_id = null;


    /**
     * ilVerDatAsDshPlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     */
    public function exchangeUIRendererAfterInitialization(Container $dic) : Closure
    {
        return CustomInputGUIsLoaderDetector::exchangeUIRendererAfterInitialization();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function isValidParentType(/*string*/ $a_type) : bool
    {
        // Allow for customizing course page (cont), but not for content page (copa) and learning module (lm)
        return $a_type === 'cont';
    }


    /**
     * @inheritDoc
     */
    public function onClone(/*array*/ &$properties, /*string*/ $plugin_version) : void
    {

    }


    /**
     * @inheritDoc
     */
    public function onDelete(/*array*/ $properties, /*string*/ $plugin_version) : void
    {
        if (self::dic()->ctrl()->getCmd() !== "moveAfter") {

        }
    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null) : void
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();
    }


    /**
     * @inheritDoc
     */
    protected function deleteData() : void
    {
        self::verDatAsDsh()->dropTables();
    }


    /**
     * @inheritDoc
     */
    protected function shouldUseOneUpdateStepOnly() : bool
    {
        return false;
    }

    // https://docu.ilias.de/goto_docu_pg_56942_42.html
    // is loaded as soon as the option VerDatAsDsh is available in the settings
    /**
     * Get Javascript files
     */
    function getJavascriptFiles($a_mode)
    {
        // This is no longer needed, but will still be included to showcase the integration of JavaScript files
        // return array("js/example.js");
        return array();
    }

    /**
     * @return int
     * Example retrieved by https://github.com/fluxfw/SrFileObjectTypeIcons/blob/main/classes/class.ilSrFileObjectTypeIconsUIHookGUI.php
     */
    public function getCurrentRefId() : int
    {
        if (self::$current_ref_id === null) {
            self::$current_ref_id = filter_input(INPUT_GET, self::GET_PARAM_REF_ID);

            if (self::$current_ref_id === null) {
                $param_target = filter_input(INPUT_GET, self::GET_PARAM_TARGET);

                self::$current_ref_id = explode("_", $param_target)[1];
            }

            self::$current_ref_id = intval(self::$current_ref_id);
        }

        return self::$current_ref_id;
    }

}
