<?php

require_once __DIR__ . "/../vendor/autoload.php";

include_once __DIR__ . "/ChromePhp.php";

use tud\Plugins\VerDatAsDsh\Utils\VerDatAsDshTrait;
use srag\DIC\VerDatAsDsh\DICTrait;

/**
 * Class ilVerDatAsDshPluginGUI
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author            tud <tommy.kubica@tu-dresden.de>
 * @author            fluxlabs <support@fluxlabs.ch>
 *
 * @ilCtrl_isCalledBy ilVerDatAsDshPluginGUI: ilPCPluggedGUI
 */
class ilVerDatAsDshPluginGUI extends ilPageComponentPluginGUI
{

    use DICTrait;
    use VerDatAsDshTrait;

    const CMD_CANCEL = "cancel";
    const CMD_CREATE = "create";
    const CMD_EDIT = "edit";
    const CMD_INSERT = "insert";
    const CMD_UPDATE = "update";
    const PLUGIN_CLASS_NAME = ilVerDatAsDshPlugin::class;

    /**
     * @var Container
     */
    protected $dic;

    /**
     * @var ilDBInterface
     */
    private $db;

    /**
     * @var ilVerDatAsDshPlugin
     */
    protected $pl;


    /**
     * ilVerDatAsDshPluginGUI constructor
     */
    public function __construct()
    {
        global $DIC;
        $this->dic = $DIC;
        $this->db = $DIC->database();
        parent::__construct();
        $this->pl = ilVerDatAsDshPlugin::getInstance();
    }

    /**
     *
     */
    public function cancel() : void
    {
        $this->returnToParent();
    }

    /**
     * @inheritDoc
     */
    public function create() : void
    {
        $form = $this->getForm(true);
        $form->setValuesByPost();
        $this->createElement(['VerDatAsDsh']);
        $this->returnToParent();
    }

    /**
     * @inheritDoc
     */
    public function edit() : void
    {
//        $form = $this->getForm();
//
//        // self::addCreationButton($form);
//        // $lng = $this->lng;
//        // $form->addCommandButton("create_plug", $lng->txt("save"));
//
//        self::output()->output($form);
    }

    /**
     * @inheritDoc
     */
    public function executeCommand() : void
    {
        $next_class = $this->dic->ctrl()->getNextClass($this);

        switch (strtolower($next_class)) {
            default:
                $cmd = $this->dic->ctrl()->getCmd();

                switch ($cmd) {
                    case self::CMD_CANCEL:
                    case self::CMD_CREATE:
                    case self::CMD_EDIT:
                    case self::CMD_INSERT:
                    case self::CMD_UPDATE:
                        $this->{$cmd}();
                        break;

                    default:
                        break;
                }
                break;
        }
    }

    /**
     * @inheritDoc
     */
    public function getElementHTML(/*string*/ $a_mode, array $a_properties, /*string*/ $plugin_version) : string
    {
        // Check, whether the element is in the edit or presentation-mode and whether an VerDatAsDsh-Element exist
        if (in_array($a_mode, ['edit', 'presentation']) && in_array('VerDatAsDsh', $a_properties)) {
            // TODO: Remove, if fully debugged
//            file_put_contents('console.log', print_r($_SESSION['userIdent'] . "\n", true), FILE_APPEND);
//            file_put_contents('console.log', print_r($_SESSION['jwt'] . "\n", true), FILE_APPEND);
//            file_put_contents('console.log', '-----', FILE_APPEND);
            // API specific variable
            $filteredSubObjects = [];
            $useAPI = false;
            $courseId = $refId = $this->pl->getCurrentRefId(); // $_GET['ref_id']; (this does not always work)
            // https://stackoverflow.com/a/29147028/3623608
            $courseNode = (object) [];
            $modules = [];
            $interactiveTasks = [];
            $tests = [];
            // Check, whether the current user should be able to edit the knowledge_structure or just view it
            $hasReadAccess = $this->dic->access()->checkAccessOfUser(
                $this->dic->user()->getId(),
                'read', 'read',
                (int) $courseId
            );
            $hasWriteAccess = $this->dic->access()->checkAccessOfUser(
                $this->dic->user()->getId(),
                'write', 'write',
                (int) $courseId
            );
            // Return, if the user has neither read nor write access
            if (!$hasReadAccess && !$hasWriteAccess) {
                return '';
            }
            // Check, whether the user is a student (read only) or a lecturer (both read and write)
            $canViewOnly = $hasReadAccess && !$hasWriteAccess;

            // BEGIN: Retrieve token (similar to Chatbot-Plugin)
            // Retrieve settings of the plugin
            $settings = new ilSetting(ilVerDatAsDshPlugin::PLUGIN_ID);
            if (!$settings) {
                return '';
            }
            $lrsTypeId = $settings->get('lrs_type_id', 0);
            $backendURL = $settings->get('backend_url', 0);
            if (!$lrsTypeId || !$backendURL) {
                return '';
            }
            $lrsType = $lrsTypeId ? new ilCmiXapiLrsType($lrsTypeId) : null;
            if (!$lrsType) {
                return '';
            }

            // Distinction between ILIAS version 6 and 7 is made
            $nameMode = isset(array_flip(get_class_methods($lrsType))['getPrivacyName']) ? $lrsType->getPrivacyIdent() : $lrsType->getUserIdent();
            $userIdent = ilCmiXapiUser::getIdent($nameMode, $this->dic->user());

            // Check if an expireDate is set and if so, whether it is exceeded
            if (!empty($_SESSION['expireDate'])) {
                if ($_SERVER['REQUEST_TIME'] > $_SESSION['expireDate']) {
                    $_SESSION['userIdent'] = null;
                    $_SESSION['jwt'] = null;
                    $_SESSION['expireDate'] = null;
                }
            }

            // At least one session variable is not set
            // As the session terminates on logout, it is not required to check the userIdent for a new logged in user
            if (empty($_SESSION['userIdent']) || empty($_SESSION['jwt'])) {
                // Prevent crash when backend is unreachable
                try {
                    // Make a request to the VerDatAs-Backend to retrieve the user token, as we need the user ID
                    $verDatAsBackendRequest = new ilVerDatAsDshHttpRequest(
                        $backendURL
                    );
                    $responseBody = $verDatAsBackendRequest->sendPost('/api/v1/auth/login', array('actorAccountName' => $userIdent));

                    // Decode JWT Token
                    // https://www.converticacommerce.com/support-maintenance/security/php-one-liner-decode-jwt-json-web-tokens/
                    $arr_body = json_decode($responseBody);
                    $token = $arr_body->token;
                    $parsedToken = json_decode(base64_decode(str_replace('_', '/', str_replace('-', '+', explode('.', $token)[1]))));
                    $ident = $parsedToken->sub;
                    $expireDate = $parsedToken->exp;

                    // Define session variables
                    $_SESSION['jwt'] = $token;
                    $_SESSION['userIdent'] = $ident;
                    $_SESSION['expireDate'] = $expireDate;
                } catch (Exception $e) {
                    file_put_contents('console.log', "An error occurred \n", FILE_APPEND);
                }
            } else {
                $token = $_SESSION['jwt'];
            }

            // Do not show dashboard when backend cannot be accessed
            if (!$token) {
                return '';
            }
            // END: Retrieve token

            // TODO: Do we really need the API to just retrieve the elements?
            // For now, it would be "overkill" to use the API just to retrieve the elements of a course
            if ($useAPI) {
                $apiFile = "./Customizing/global/plugins/Services/EventHandling/EventHook/Api/classes/IliasAPIControl/IliasAPIControl.php";
                require_once($apiFile);
                $this->api = new \IliasAPIControl\IliasAPIControl('verdatas');
                try {
                    $this->api->login(
                        'root',
                        'verdatas1909'
                    );
                    $courseNode = $this->api->course->getData($courseId);
//                    ChromePhp::log('courseData', $courseNode);
                    $getIliasObjectTypes = $this->api->role->getIliasObjectTypes();
//                    ChromePhp::log('getIliasObjectTypes', $getIliasObjectTypes);
                    $courseSubObjects = $this->api->course->getSubObjects($courseId);
//                    ChromePhp::log('courseSubObjects', $courseSubObjects);
                    foreach ($courseSubObjects as $subObject) {
                        $parsedSubObject = (object) $subObject;
                        if ($parsedSubObject->parent !== '1') {
                            $filteredSubObjects[] = $parsedSubObject->child;
                        }
                    }
//                    ChromePhp::log('filteredSubObjects', $filteredSubObjects);
                } catch (Exception $e) {
                    ChromePhp::log('error', $e);
                }
            } // Do not use the API
            else {
                ChromePhp::log('Else (not using API)');
                include_once('./Services/Tree/classes/class.ilTree.php');
                require_once('./Modules/LearningModule/classes/class.ilObjLearningModule.php');
                // Use code from vAPI to get subTree
                $tree = new \ilTree(1);
                // type: "crs", ref_id -> use for loading knowledge_structure
                $courseNode = $tree->getNodeData($courseId);
                ChromePhp::log('Course Node', $courseNode);
                $courseNode['object_id'] = $this->getObjectPermaLink('crs', $courseId, $courseNode['obj_id']);
                // Currently supported module types by VerDatAs
                $moduleTypesArray = array('lm', 'cmix', 'tst');
                // Sort learning modules by their titles
                $subNodes = $tree->getSubTree($courseNode);
                usort($subNodes, function($a, $b) {
                    // https://www.php.net/manual/en/function.usort.php
                    // "->" is used to call a method, or access a property, on the object of a class
                    // "['prop']" is used to access a key of an array (?)
                    // In this case, the "->" notation does not work
                    return strcmp($a['title'], $b['title']);
                });
                foreach ($subNodes as $subNode) {
                    // Check if the type is a module
                    if (in_array($subNode['type'], $moduleTypesArray)) {
                        ChromePhp::log($subNode);
                        // For learning module ILIAS retrieve the inner structure (chapters, tasks) as well
                        if ($subNode['type'] === 'lm') {
                            try {
                                // Use code from Sebastian Heiden's extension of the REST plugin
                                // https://github.com/spyfly/Ilias.RESTPlugin/blob/feature/sr-app-routes/RESTController/extensions/learning_module_v1/models/ILIASAppModel.php#L107
                                $learningModule = new \ilObjLearningModule($subNode['ref_id']);
                                $learningModuleObject = \ilObjectFactory::getInstanceByRefId($subNode['ref_id']);
                                $subNode['object_id'] = $this->getObjectPermaLink('lm', $subNode['ref_id'], $learningModule->getId());
                                $lmTree = $learningModule->getTree();
//                                ChromePhp::log('lmTree', $lmTree);
                                $lmTreeContent = $lmTree->getSubTree($lmTree->getNodeData($lmTree->readRootId()));
//                                ChromePhp::log('lmTreeContent', $lmTreeContent);
                                $lmContent = array();
                                $lmChapters = array();
                                $lmSubChapters = array();
                                $lmPages = array();
                                // iterate tree and hold objects
                                foreach ($lmTreeContent as $lmObj) {
                                    if ($lmObj['type'] == 'du') {
                                        continue;
                                    }

                                    $objDetails = [
                                        "title" => $lmObj['title'],
                                        "type" => $lmObj['type'],
                                        "parent" => $lmObj['parent'],
                                        "obj_id" => $lmObj['obj_id']
                                    ];
                                    // TODO: This is necessary to retrieve the details of the page
                                    if ($lmObj['type'] == 'pg') {
                                        $lmPage = new \ilLMPage($lmObj['obj_id']);
                                        $objDetails['object_id'] = $this->getObjectPermaLink('pg', $subNode['ref_id'], $lmPage->getId());
                                        $objDetails = array_merge($objDetails, $this->getPageDetails($lmPage, $subNode['ref_id'], $objDetails['object_id']));
                                        $lmPages[] = $objDetails;
                                    }

                                    if ($lmObj['type'] == 'st') {
                                        // $lmStructureObject = new \ilStructureObject($learningModule, $lmObj['obj_id']);
                                        // $lmStructureObject->getId() should be equivalent to $lmObj['obj_id']
                                        $objDetails['object_id'] = $this->getObjectPermaLink('st', $subNode['ref_id'], $lmObj['obj_id']);
                                        // for chapters within modules, the parent ID is '1'
                                        if ($lmObj['parent'] == '1') {
                                            $lmChapters[] = $objDetails;
                                        } else {
                                            $lmSubChapters[] = $objDetails;
                                        }
                                    }

                                    $lmContent[] = $objDetails;
                                }
                                // iterate pages and put them as attributes of the chapters or sub-chapters
                                foreach ($lmPages as $page) {
                                    $foundKey = array_search($page['parent'], array_column($lmChapters, 'obj_id'));
                                    $foundSubChapterKey = array_search($page['parent'], array_column($lmSubChapters, 'obj_id'));
                                    if ($foundKey !== false) {
                                        $chapterFound = $lmChapters[$foundKey];
                                        $pages = array();
                                        // $pages already exists
                                        if ($chapterFound['pages']) {
                                            $pages = $chapterFound['pages'];
                                        }
                                        if ($page['questionsXhfp']) {
                                            $page['interactiveTasks'] = $page['questionsXhfp'];
                                        }
                                        $pages[] = $page;
                                        $chapterFound['pages'] = $pages;
                                        // Also hold the interactive tasks of pages in the chapter
                                        if ($page['questionsXhfp']) {
                                            if (!$chapterFound['interactiveTasks']) {
                                                $chapterFound['interactiveTasks'] = $page['questionsXhfp'];
                                            } else {
                                                $chapterFound['interactiveTasks'] = array_merge($chapterFound['interactiveTasks'], $page['questionsXhfp']);
                                            }
                                        }
                                        // write back chapter found
                                        $lmChapters[$foundKey] = $chapterFound;
                                    } else {
                                        if ($foundSubChapterKey !== false) {
                                            $subChapterFound = $lmSubChapters[$foundSubChapterKey];
                                            $pages = array();
                                            // $pages already exists
                                            if ($subChapterFound['pages']) {
                                                $pages = $subChapterFound['pages'];
                                            }
                                            $pages[] = $page;
                                            $subChapterFound['pages'] = $pages;
                                            // write back chapter found
                                            $lmSubChapters[$foundSubChapterKey] = $subChapterFound;
                                            // TODO: Interactive tasks in sub chapters
                                        }
                                    }
                                }
                                // iterate sub-chapters and put them as attributes of the chapters
                                foreach ($lmSubChapters as $subChapter) {
                                    $foundKey = array_search($subChapter['parent'], array_column($lmChapters, 'obj_id'));
                                    if ($foundKey) {
                                        $chapterFound = $lmChapters[$foundKey];
                                        $subChapters = array();
                                        // subChapters already exists
                                        if ($chapterFound['subChapters']) {
                                            $subChapters = $chapterFound['subChapters'];
                                        }
                                        $subChapters[] = $subChapter;
                                        $chapterFound['subChapters'] = $subChapters;
                                        // write back chapter found
                                        $lmChapters[$foundKey] = $chapterFound;
                                    }
                                }
                                // TODO: 'content' is not yet used
                                // $subNode['content'] = $lmContent;
                                $subNode['chapters'] = $lmChapters;
                            } catch (Exception $e) {
                                ChromePhp::log('error', $e);
                            }
                        }
                        else if ($subNode['type'] === 'tst') {
                            $tests[] = $subNode;
                        }
                        else if ($subNode['type'] === 'cmix') {
                            ChromePhp::log('Type cmix detected, but not yet taken into account.');
                        }
                        $modules[] = $subNode;
                    }
                    // TODO: When reworking, this might be moved a few lines down
                    $courseNode['modules'] = $modules;
                    $courseNode['tests'] = $tests;
                }

//                ChromePhp::log($modules);
//                ChromePhp::log('-----');
//                ChromePhp::log($interactiveTasks);
            }

            // Add custom template, whose will load the JavaScript file
            $tpl = $this->getPlugin()->getTemplate('dashboard.html');

            // Add templatePath variable to specify the current path
            $templatePath = $this->getPlugin()->getDirectory() . '/templates';
            $tpl->setVariable('TEMPLATE_PATH', $templatePath);
            // This allows to hide the buttons if the user cannot edit the knowledge structure
            if ($canViewOnly) {
                $tpl->setVariable('VIEW_ONLY', 'hidden');
            }

            // TODO: Calling methods directly does not work
            // Current workaround: Use CustomEvent to send the required data to the code in Vue
            // First event: Templates path
            $this->dic->ui()->mainTemplate()->addOnLoadCode('document.dispatchEvent(new CustomEvent("init-dashboard", { "detail": ' . json_encode($templatePath) . '  }))');
            // Second event: Data for the editor
            // $this->dic->ui()->mainTemplate()->addOnLoadCode('init(' . json_encode($courseNode) . ', ' . json_encode($token) . ', ' . json_encode($backendURL) . ', ' . $canViewOnly . ');');

            $initGraphData = '{
              "courseNode": ' . json_encode($courseNode) .',
              "token": ' . json_encode($token) .',
              "backendURL": ' . json_encode($backendURL) .',
              "canViewOnly": ' . json_encode($canViewOnly) .'
            }';
//            $initGraphData = array(
//                courseNode => json_encode($courseNode),
//                token => json_encode($token),
//                backendURL => json_encode($backendURL),
//                canViewOnly => $canViewOnly
//            );
            $this->dic->ui()->mainTemplate()->addOnLoadCode('document.dispatchEvent(new CustomEvent("init-graph", { "detail": ' . $initGraphData . '  }))');
            return $tpl->get();
        }
        return '';
    }

    // Retrieved from code written by Sebastian Heiden:
    // https://github.com/spyfly/Ilias.RESTPlugin/blob/af267b4cbb71d452889b5159fda9acd7c04b1e86/RESTController/extensions/learning_module_v1/models/ILIASAppModel.php#L142
    private function getPageDetails($pageObj, $learningModuleRefId, $pageObjectId)
    {
        $pageObj->buildDom();
        $questionIds = $pageObj->getQuestionIds();
        $pool = new \ilObjQuestionPool();
        $xmlContent = $pageObj->getXMLContent();

        preg_match_all('/<Plugged PluginName=\\"H5PPageComponent\\" [^>]*><PluggedProperty Name=\\"content_id\\">([0-9]*)<\/PluggedProperty><\/Plugged>/', $xmlContent, $h5pRaw);
        $questionsXhfp = [];
        if (count($h5pRaw[1]) > 0) {
            $db = $this->db;
            foreach ($h5pRaw[1] as $h5pContentId) {
                $hset = $db->query("SELECT name, parameters, rep_robj_xhfp_cont.title, content_id FROM rep_robj_xhfp_lib LEFT JOIN rep_robj_xhfp_cont ON rep_robj_xhfp_lib.library_id = rep_robj_xhfp_cont.library_id WHERE rep_robj_xhfp_cont.content_id = " . $db->quote($h5pContentId,
                        "integer"));
                // TODO: The attribute "parameter" gets lost at this position, as the code crashes otherwise
                // $row = $db->fetchAssoc($hset);
                // https://stackoverflow.com/a/29147028/3623608
                $h5pObject = array();
                while ($row = $db->fetchAssoc($hset)) {
//                    ChromePhp::log($row);
                    $h5pObject['name'] = $row['name'];
                    $h5pObject['title'] = $row['title'];
                    $h5pObject['content_id'] = $row['content_id'];
                    $h5pObject['object_id'] = $this->getObjectPermaLink('h5p', $learningModuleRefId, $h5pContentId, $pageObj->getId());
                    $h5pObject['page_object_id'] = $pageObjectId;
                    // Only add question if it exists
                    $questionsXhfp[] = $h5pObject;
                }
            }
        }

        return [
            "xmlContent" => $xmlContent,
            "multimediaXml" => $pageObj->getMultimediaXML(),
            "questionsXml" => count($questionIds) > 0 ? $pool->questionsToXML($questionIds) : "",
            "questionsXhfp" => $questionsXhfp
        ];
    }

    /**
     * @inheritDoc
     */
    public function insert() : void
    {
        $form = $this->getForm(true);

        self::addCreationButton($form);
        $form->addCommandButton('cancel', $this->lng->txt('cancel'));
        $form->setFormAction($this->dic->ctrl()->getFormAction($this, 'create'));

        self::output()->output($form);
    }

    /**
     *
     */
    public function update() : void
    {
        $form = $this->getForm();

        $form->setValuesByPost();

        if (!$form->checkInput()) {
            self::output()->output($form);

            return;
        }

        $properties = $this->getProperties();

        // TODO: Implement update

        $this->updateElement($properties);

        $this->returnToParent();
    }

    /**
     * @return ilPropertyFormGUI
     */
    protected function getForm($a_create = false) : ilPropertyFormGUI
    {
        $form = new ilPropertyFormGUI();
        $form->setTitle('Test Form');
        $section = new ilFormSectionHeaderGUI();
        $section->setTitle('Test Section');
        $form->addItem($section);
        // example item
        $item = new ilRadioGroupInputGUI('Type', 'type_id');
        $item->setRequired(true);
        $option = new ilRadioOption('A', '1234', 'Description 1234');
        $item->addOption($option);
        $option = new ilRadioOption('B', '9876', 'Description 9876');
        $item->addOption($option);
        $form->addItem($item);

        // TODO: Implement getForm
        // TODO: Use seperate class

        return $form;
    }

    /**
     * Retrieved from Events2Lrs
     * @param string $objectType
     * @param int $referenceId
     * @param int $objectId
     * @param bool $withObjId
     * @return string
     * Expected behavior (similar to ILIAS perma link):
     * - Course: http://localhost:8080/goto.php?target=crs_82&client_id=default&obj_id_lrs=311
     * - Learning module: http://localhost:8080/goto.php?target=lm_83&client_id=default&obj_id_lrs=315
     * - Chapter: http://localhost:8080/goto.php?target=st_8_83&client_id=default&obj_id_lrs=315
     * - Page within learning module: http://localhost:8080/goto.php?target=pg_11_83&client_id=default&obj_id_lrs=315
     * - H5P question on page of learning module: http://localhost:8080/goto.php?target=pg_11_83&client_id=default&h5p_object_id=11&obj_id_lrs=315
     */
    public function getObjectPermaLink(string $objectType, int $referenceId, int $objectId, int $pageId = -1, bool $withObjId = true)
    {
        $stringIds = '';
        $object = \ilObjectFactory::getInstanceByRefId($referenceId);
        $objId = preg_replace('%([\D].*)%', '', $object->getId());

        if ($withObjId) {
            if ($objectType == 'h5p') {
                $stringIds .= '&h5p_object_id=' . $objectId;
            }
            $stringIds .= '&obj_id_lrs=' . $objId;
        }

        $reference = '';
        switch ($objectType) {
            case 'crs':
                $reference = $referenceId;
                break;
            case 'lm':
                $reference = $referenceId;
                break;
            case 'st':
                $reference = $objectId . '_' . $referenceId;
                break;
            case 'pg':
                $reference = $objectId . '_' . $referenceId;
                break;
            case 'h5p':
                // TODO: Dirty fix for setting the URL to the learning module
                $objectType = 'pg';
                $reference = $pageId . '_' . $referenceId;
                break;
            default:
                $reference = $referenceId;
        }

        return ilLink::_getLink($reference, $objectType) . $stringIds;
    }

    /**
     * @return ilVerDatAsDshPageComponentPlugin
     */
    public function getPlugin()
    {
        return parent::getPlugin();
    }
}
