<?php

namespace tud\Plugins\VerDatAsDsh\Config;

use tud\Plugins\VerDatAsDsh\Config\Form\FormBuilder;
use tud\Plugins\VerDatAsDsh\Utils\VerDatAsDshTrait;
use ilVerDatAsDshPlugin;
use srag\ActiveRecordConfig\VerDatAsDsh\Config\AbstractFactory;

/**
 * Class Factory
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package tud\Plugins\VerDatAsDsh\Config
 *
 * @author tud <tommy.kubica@tu-dresden.de>
 * @author fluxlabs <support@fluxlabs.ch>
 */
final class Factory extends AbstractFactory
{

    use VerDatAsDshTrait;

    const PLUGIN_CLASS_NAME = ilVerDatAsDshPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Factory constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @param ConfigCtrl $parent
     *
     * @return FormBuilder
     */
    public function newFormBuilderInstance(ConfigCtrl $parent) : FormBuilder
    {
        $form = new FormBuilder($parent);

        return $form;
    }
}
