<?php

namespace tud\Plugins\VerDatAsDsh\Config;

use tud\Plugins\VerDatAsDsh\Config\Form\FormBuilder;
use tud\Plugins\VerDatAsDsh\Utils\VerDatAsDshTrait;
use ilVerDatAsDshPlugin;
use srag\ActiveRecordConfig\VerDatAsDsh\Config\AbstractFactory;
use srag\ActiveRecordConfig\VerDatAsDsh\Config\AbstractRepository;
use srag\ActiveRecordConfig\VerDatAsDsh\Config\Config;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package tud\Plugins\VerDatAsDsh\Config
 *
 * @author tud <tommy.kubica@tu-dresden.de>
 * @author fluxlabs <support@fluxlabs.ch>
 */
final class Repository extends AbstractRepository
{

    use VerDatAsDshTrait;

    const PLUGIN_CLASS_NAME = ilVerDatAsDshPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     *
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }


    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            FormBuilder::KEY_SOME => Config::TYPE_STRING
        ];
    }


    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilVerDatAsDshPlugin::PLUGIN_ID . "_config";
    }
}
